name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./... -coverprofile coverage.out -covermode count
      
    - name: Quality Gate - Test Coverage
      env: 
        TESTCOVERAGE_TRESHOLD: 0
      run: |
            echo "Quality Gate: checking test coverage is above treshold..."
            echo "Treshhold :$TESTCOVERAGE_TRESHOLD %"
            totalCoverage=`go tool cover -func coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage: $totalCoverage %"
            if ($totalCoverage > $TESTCOVERAGE_TRESHOLD) 
              echo "OK
            else
              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
            fi

    - name: Build
      run: go build -v ./...
            
